name: Publish Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
#       - name: Ready to build  and deploy 🤓
#         uses: fifsky/dingtalk-action@master
#         with:
#           url: ${{ secrets.DINGTALK_WEBHOOK }}
#           type: text
#           content: Github：Data Structure and Algorithms Guidebook 构建开始
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install Pnpm
        run: corepack enable
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: doc_build
          target-folder: builder
          clean: true
#       - name: Complete ✅
#         uses: fifsky/dingtalk-action@master
#         with:
#           url: ${{ secrets.DINGTALK_WEBHOOK }}
#           type: text
#           content: Github：Data Structure and Algorithms Guidebook 构建完成
